version: "3.9"
services:
  web:
    build:
      context: ./vulApp
      dockerfile: Dockerfile
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./vulApp/src:/usr/src/app
    restart: always
    networks:
      vul-net:
        ipv4_address: 192.168.100.10
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    restart: always
    networks:
      vul-net:
        ipv4_address: 192.168.100.20

networks:
  vul-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24